/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class sdk_Say */

#ifndef _Included_sdk_Say
#define _Included_sdk_Say
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     sdk_Say
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
  JNIEXPORT jstring JNICALL Java_sdk_Say_sayHello(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
