/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class sdk_Obj */

#ifndef _Included_sdk_Obj
#define _Included_sdk_Obj
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     sdk_Obj
 * Method:    createUser
 * Signature: (Ljava/lang/String;D)Lsdk/UserData;
 */
  JNIEXPORT jobject JNICALL Java_sdk_Obj_createUser(JNIEnv *, jobject, jstring, jdouble);

  /*
 * Class:     sdk_Obj
 * Method:    printUserData
 * Signature: (Lsdk/UserData;)Ljava/lang/String;
 */
  JNIEXPORT jstring JNICALL Java_sdk_Obj_printUserData(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
