/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class sdk_Param */

#ifndef _Included_sdk_Param
#define _Included_sdk_Param
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     sdk_Param
 * Method:    sumIntegers
 * Signature: (II)J
 */
  JNIEXPORT jlong JNICALL Java_sdk_Param_sumIntegers(JNIEnv *, jobject, jint, jint);

  /*
 * Class:     sdk_Param
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
  JNIEXPORT jstring JNICALL Java_sdk_Param_sayHelloToMe(JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
